---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lstocks3/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp version.txt $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R legal $DEPLOYPATH
